#!/usr/bin/env bash

PROJECT_ROOT=$(realpath `dirname "$0"`/../)
php7=$PROJECT_ROOT/shortcuts/php7
php7="$php7 -dxdebug.remote_enable=0"
COMPOSER="$PROJECT_ROOT/composer.phar"

if [[ ! -f "$COMPOSER" ]]; then
    COMPOSER_SETUP="$PROJECT_ROOT/composer-setup.php"
    $php7 -r "readfile('https://getcomposer.org/installer');" > $COMPOSER_SETUP
    $php7 $COMPOSER_SETUP
    rm $COMPOSER_SETUP
fi

$php7 -dmemory_limit=-1 $COMPOSER "$@"
