#!/bin/bash

while read -r file;
do
  file=${file:1}
  file="$(echo -e "${file}" | tr -d '[[:space:]]')"
  echo $file
  if [[ $file = *.php ]];
  then
    php vendor/fabpot/php-cs-fixer/php-cs-fixer --config-file .php_cs fix "$file"
    git add "$file"
  fi
done < <(git diff --cached --name-status --diff-filter=ACM)
